name       : screenshot-applet
version    : 0.3.5
release    : 4
source     :
    - https://github.com/cybre/screenshot-applet/archive/0.3.5.tar.gz : 9ae5cf982c271f8c5b9f28086a15e2e1cc685c5afe5d67807a0141048026f502
license    : GPL-2.0
component  : budgie.desktop
summary    : A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
description: |
    A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
