name       : budgie-screenshot-applet
version    : 0.4.3
release    : 19
source     :
    - https://github.com/cybre/budgie-screenshot-applet/archive/v0.4.3.tar.gz : 0a39cd01a76aaa825caccd62a46833163e113098f359074171eb134a27c7b67b
license    : GPL-2.0
component  : desktop.budgie
summary    : Take a screenshot of your desktop, a window or region; save to disk and
    upload.
description: |
    Take a screenshot of your desktop, a window or region; save to disk and upload.
replaces   : screenshot-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
