name       : budgie-screenshot-applet
version    : 0.3.9.1
release    : 11
source     :
    - https://github.com/cybre/budgie-screenshot-applet/releases/download/0.3.9.1/budgie-screenshot-applet-0.3.9.1.tar.xz : 18e6ee91822b1e57a7dedc778f679f4a1dd84d3a84061eb5695faf80f1dab499
license    : GPL-2.0
component  : desktop.budgie
summary    : A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
description: |
    A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
replaces   : screenshot-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - vala
rundeps    :
    - gnome-screenshot
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
