name       : budgie-screenshot-applet
version    : 0.4.3
release    : 28
source     :
    - git|https://github.com/cybre/budgie-screenshot-applet.git : 9e79e58419d42ba4f338a5cd84fa35d2c5ddb5da
license    : GPL-2.0-or-later
component  : desktop.budgie
summary    : Take a screenshot of your desktop, a window or region; save to disk and upload.
description: |
    Take a screenshot of your desktop, a window or region; save to disk and upload.
replaces   : screenshot-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
