name       : screenshot-applet
version    : 0.3.4
release    : 3
source     :
    - https://github.com/cybre/screenshot-applet/archive/0.3.4.tar.gz : 8eb384bd9e7b84c146bc6536b095fb223560cc69fabf6452c4e63f39c1cc79a7
license    : GPL-2.0
component  : budgie.desktop
summary    : A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
description: |
    A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
