name       : budgie-screenshot-applet
version    : 0.4.1
release    : 14
source     :
    - https://github.com/cybre/budgie-screenshot-applet/archive/0.4.1.tar.gz : 6f72da502cc4e8812da8ff4d0096f65e2dcd663b254b15178e5501b32802970e
license    : GPL-2.0
component  : desktop.budgie
summary    : Take a screenshot of your desktop, a window or region; save to disk and upload.
description: |
    Take a screenshot of your desktop, a window or region; save to disk and upload.
replaces   : screenshot-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    mkdir build
    pushd build
    %meson_configure ..
build      : |
    pushd build
    %meson_build
install    : |
    pushd build
    %meson_install
