name       : budgie-screenshot-applet
version    : 0.3.8
release    : 7
source     :
    - https://github.com/cybre/budgie-screenshot-applet/archive/0.3.8.tar.gz : 49cf8cc7c69e596f9e5507b1f882b47c04a685e7ce19b546902e26e3551fc970
license    : GPL-2.0
component  : desktop.budgie
summary    : A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
description: |
    A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
replaces   : screenshot-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
