name       : budgie-screenshot-applet
version    : 0.3.9
release    : 8
source     :
    - https://github.com/cybre/budgie-screenshot-applet/archive/v0.3.9.tar.gz : 4717a809fd9709ad1a79fdc242675213089c154444ff777ee99f72e5bea6b4ad
license    : GPL-2.0
component  : desktop.budgie
summary    : A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
description: |
    A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
replaces   : screenshot-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
