name       : screenshot-applet
version    : 0.3.2
release    : 1
source     :
    - https://github.com/cybre/screenshot-applet/archive/0.3.2.tar.gz : 2ad768aa28eb90515b0dc6b38c65026ec1c51488f27cd86cb15dc0767ef3c8d3
license    : GPL-2.0
component  : budgie.desktop
summary    : A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
description: |
    A Budgie applet for taking and uploading screenshots to Imgur and Imagebin.
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(rest-0.7)
    - vala
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install