name       : budgie-screenshot-applet
version    : 0.4.0
release    : 13
source     :
    - https://github.com/cybre/budgie-screenshot-applet/archive/0.4.0.tar.gz : bc6e0151403212b10e94755c4af7abbe365d7bf81a331ab2da1e23e54d54e66c
license    : GPL-2.0
component  : desktop.budgie
summary    : Take a screenshot of your desktop, a window or region; save to disk and upload.
description: |
    Take a screenshot of your desktop, a window or region; save to disk and upload.
replaces   : screenshot-applet
builddeps  :
    - pkgconfig(budgie-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - meson
    - vala
setup      : |
    mkdir build
    pushd build
    %meson_configure ..
build      : |
    pushd build
    %meson_build
install    : |
    pushd build
    %meson_install
